defaults:
  - model: mlp4
  - lossfun: qubic_1d

trainer:
  optim:
    type: Adam
    lr: 5.e-4
    betas: [0.9, 0.999]
    eps: 1.e-8
    weight_decay: 0
  resume: false
  resume_dir:
  epochs: 500
  initialization:
    initialize: true
    init_condition: [0.96] # Local minimum of qubic_1d
    timeout_s: 10.0

logs:
  save_interval: 100
