defaults:
  - model: mlp9
  - lossfun: ackley

trainer:
  optim:
    type: Adam
    lr: 5.e-4
    betas: [0.9, 0.999]
    eps: 1.e-8
    weight_decay: 0
  resume: false
  resume_dir:
  epochs: 500
  initialization:
    initialize: true
    init_condition: [10.0]
    timeout_s: 10.0

logs:
  save_interval: 100
